### ISSUE TITLE
the onClientAcceptButton event exists but does not work

### ISSUE THREAD

**Issue by DenisGabriel45** [Allerek/MTA-RAGE-NativeUI#3]
It's only added in ```c_button.lua``` as:
```lua
addEvent("onClientAcceptButton", true)
```
But in ```c_MTA-V-Native-UI.lua``` at:
```lua
function nativeEnter()
    if not isNativeShown then return end
    if #menus[activeMenu].items == 0 then return end

    if menus[activeMenu].items[menus[activeMenu].activeItem].type == "switch" then
        local activeItem = menus[activeMenu].items[menus[activeMenu].activeItem]
        local actualSwitchIndex = activeItem.currentPosition
        local actualSwitchValue = activeItem.values[tonumber(actualSwitchIndex)]
        triggerEvent("onClientAcceptNativeSwitch", activeItem.element, actualSwitchValue)
    elseif menus[activeMenu].items[menus[activeMenu].activeItem].type == "checkbox" then
        menus[activeMenu].items[menus[activeMenu].activeItem].selected = not menus[activeMenu].items[menus[activeMenu].activeItem].selected
        playNativeSound()
        triggerEvent("onClientNativeCheckBoxChange", menus[activeMenu].items[menus[activeMenu].activeItem].element, menus[activeMenu].items[menus[activeMenu].activeItem].selected)
	end
end
```
It's not

**Comment by DenisGabriel45** [comment]
> It's only added in `c_button.lua` as:
> 
> ```lua
> addEvent("onClientAcceptButton", true)
> ```
> 
> But in `c_MTA-V-Native-UI.lua` at:
> 
> ```lua
> function nativeEnter()
>     if not isNativeShown then return end
>     if #menus[activeMenu].items == 0 then return end
> 
>     if menus[activeMenu].items[menus[activeMenu].activeItem].type == "switch" then
>         local activeItem = menus[activeMenu].items[menus[activeMenu].activeItem]
>         local actualSwitchIndex = activeItem.currentPosition
>         local actualSwitchValue = activeItem.values[tonumber(actualSwitchIndex)]
>         triggerEvent("onClientAcceptNativeSwitch", activeItem.element, actualSwitchValue)
>     elseif menus[activeMenu].items[menus[activeMenu].activeItem].type == "checkbox" then
>         menus[activeMenu].items[menus[activeMenu].activeItem].selected = not menus[activeMenu].items[menus[activeMenu].activeItem].selected
>         playNativeSound()
>         triggerEvent("onClientNativeCheckBoxChange", menus[activeMenu].items[menus[activeMenu].activeItem].element, menus[activeMenu].items[menus[activeMenu].activeItem].selected)
> 	end
> end
> ```
> 
> It's not

I made the event to be functional, just replace ```navigateEnter``` function with this one:
```lua
function nativeEnter()
    if not isNativeShown then return end
    if #menus[activeMenu].items == 0 then return end

    if menus[activeMenu].items[menus[activeMenu].activeItem].type == "switch" then
        local activeItem = menus[activeMenu].items[menus[activeMenu].activeItem]
        local actualSwitchIndex = activeItem.currentPosition
        local actualSwitchValue = activeItem.values[tonumber(actualSwitchIndex)]
        triggerEvent("onClientAcceptNativeSwitch", activeItem.element, actualSwitchValue)
    elseif menus[activeMenu].items[menus[activeMenu].activeItem].type == "checkbox" then
        menus[activeMenu].items[menus[activeMenu].activeItem].selected = not menus[activeMenu].items[menus[activeMenu].activeItem].selected
        playNativeSound()
        triggerEvent("onClientNativeCheckBoxChange", menus[activeMenu].items[menus[activeMenu].activeItem].element, menus[activeMenu].items[menus[activeMenu].activeItem].selected)
    elseif menus[activeMenu].items[menus[activeMenu].activeItem].type == "button" then
	 menus[activeMenu].items[menus[activeMenu].activeItem].selected = true
         playNativeSound()
	 triggerEvent("onClientAcceptButton", menus[activeMenu].items[menus[activeMenu].activeItem].element, 
         menus[activeMenu].items[menus[activeMenu].activeItem].selected)
    end
end
```

**Comment by Allerek** [comment]
If you could make this a Pull Request it would be nice
